# Generated by Django 4.2.7 on 2023-11-30 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClothApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productmodel',
            table='product',
        ),
    ]
