# Generated by Django 4.2.7 on 2023-11-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClothApp', '0002_alter_productmodel_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Catagory_name',
            new_name='Category_name',
        ),
    ]
